### ISSUE TITLE
Outdated styles

### ISSUE THREAD

**Issue by jsmnbom** [mdn/web-tech-games#1]
[https://developer.cdn.mozilla.net/static/build/styles/mdn.945582cfe665.css](https://developer.cdn.mozilla.net/static/build/styles/mdn.945582cfe665.css) seems to not be a valid URL anymore.

Short term workahead is to simply change the <link> tag to `https://developer.cdn.mozilla.net/static/build/styles/mdn.30f0496a31e2.css` or `https://cdn.mdn.mozilla.net/static/build/styles/mdn.30f0496a31e2.css`

But this is probably gonna break once again the next time the styles are updated on the main site, so a more permanent solution is definitely needed.

**Comment by jsmnbom** [comment]
Note that this is how [https://developer.mozilla.org/en-US/docs/Games](https://developer.mozilla.org/en-US/docs/Games) looks due to the broken styles:
![screen shot 2017-10-22 at 12 51 52-fullpage](https://user-images.githubusercontent.com/3002987/31861135-dd6b48ba-b727-11e7-9dbc-5261d05b2e89.png)

**Comment by chrisdavidmills** [comment]
Argh! Thanks for pointing this out to me. To avoid further breakages, I've made a snapshot of the current MDN CSS, put it in same repo as the diagram, and linked to there instead.
